extends:
  - stylelint-config-standard-scss

# plugins:
  # - stylelint-scss

# syntax:
  # - scss

rules:
  color-function-notation: legacy
  no-descending-specificity: null
  selector-class-pattern: null

  scss/dollar-variable-pattern: null
